/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_EN 0x0100u   /*!<@brief Full drive enable */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name FC2_RXD_SDA_MOSI_DATA (coord B12), J36[8]/J47[7]/J48[15]/U109[64]/JS5[2]/FC2_SDA
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITCS42448PINS_fc2_i2s_sda_PERIPHERAL FLEXCOMM2
/*!
 * @brief Signal name */
#define BOARD_INITCS42448PINS_fc2_i2s_sda_SIGNAL RXD_SDA_MOSI_DATA
/* @} */

/*! @name FC2_TXD_SCL_MISO_WS (coord A16), J36[6]/J47[6]/J48[13]/U109[63]/JS6[2]/FC2_SCL
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITCS42448PINS_fc2_i2s_scl_PERIPHERAL FLEXCOMM2
/*!
 * @brief Signal name */
#define BOARD_INITCS42448PINS_fc2_i2s_scl_SIGNAL TXD_SCL_MISO_WS
/* @} */

/*! @name FC2_SCK (coord B17), Q4[5]
  @{ */
/* Routed pin properties */
#define BOARD_INITCS42448PINS_fc2_i2s_sck_PERIPHERAL FLEXCOMM2 /*!<@brief Peripheral name */
#define BOARD_INITCS42448PINS_fc2_i2s_sck_SIGNAL SCK           /*!<@brief Signal name */
                                                               /* @} */

/*! @name FC4_SCK (coord A6), J27[3]
  @{ */
/* Routed pin properties */
#define BOARD_INITCS42448PINS_FC4_SCK_PERIPHERAL FLEXCOMM4 /*!<@brief Peripheral name */
#define BOARD_INITCS42448PINS_FC4_SCK_SIGNAL SCK           /*!<@brief Signal name */
                                                           /* @} */

/*! @name FC4_TXD_SCL_MISO_WS (coord B6), J27[2]
  @{ */
/* Routed pin properties */
#define BOARD_INITCS42448PINS_FC4_SCL_PERIPHERAL FLEXCOMM4         /*!<@brief Peripheral name */
#define BOARD_INITCS42448PINS_FC4_SCL_SIGNAL TXD_SCL_MISO_WS       /*!<@brief Signal name */
                                                                   /* @} */

/*! @name FC4_RXD_SDA_MOSI_DATA (coord C6), JP42[2]
  @{ */
/* Routed pin properties */
#define BOARD_INITCS42448PINS_FC4_DATA_PERIPHERAL FLEXCOMM4           /*!<@brief Peripheral name */
#define BOARD_INITCS42448PINS_FC4_DATA_SIGNAL RXD_SDA_MOSI_DATA       /*!<@brief Signal name */
                                                                      /* @} */

/*! @name FC5_SCK (coord J4), J28[6]/J58[7]/ARD_SPI_CLK
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITCS42448PINS_FC5_SCK_PERIPHERAL FLEXCOMM5
/*!
 * @brief Signal name */
#define BOARD_INITCS42448PINS_FC5_SCK_SIGNAL SCK
/* @} */

/*! @name FC5_TXD_SCL_MISO_WS (coord H3), J28[5]/J45[32]/J58[5]/ARD_SPI_MISO
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITCS42448PINS_FC5_SCL_PERIPHERAL FLEXCOMM5
/*!
 * @brief Signal name */
#define BOARD_INITCS42448PINS_FC5_SCL_SIGNAL TXD_SCL_MISO_WS
/* @} */

/*! @name FC5_RXD_SDA_MOSI_DATA (coord J3), JP41[2]
  @{ */
/* Routed pin properties */
#define BOARD_INITCS42448PINS_FC5_DATA_PERIPHERAL FLEXCOMM5           /*!<@brief Peripheral name */
#define BOARD_INITCS42448PINS_FC5_DATA_SIGNAL RXD_SDA_MOSI_DATA       /*!<@brief Signal name */
                                                                      /* @} */

/*! @name FC6_SCK (coord R9), FC6_SCK
  @{ */
/* Routed pin properties */
#define BOARD_INITCS42448PINS_FC6_SCK_PERIPHERAL FLEXCOMM6 /*!<@brief Peripheral name */
#define BOARD_INITCS42448PINS_FC6_SCK_SIGNAL SCK           /*!<@brief Signal name */
                                                           /* @} */

/*! @name FC6_TXD_SCL_MISO_WS (coord P9), FC6_SCL
  @{ */
/* Routed pin properties */
#define BOARD_INITCS42448PINS_FC6_SCL_PERIPHERAL FLEXCOMM6         /*!<@brief Peripheral name */
#define BOARD_INITCS42448PINS_FC6_SCL_SIGNAL TXD_SCL_MISO_WS       /*!<@brief Signal name */
                                                                   /* @} */

/*! @name FC6_RXD_SDA_MOSI_DATA (coord T8), FC6_DATA
  @{ */
/* Routed pin properties */
#define BOARD_INITCS42448PINS_FC6_DATA_PERIPHERAL FLEXCOMM6           /*!<@brief Peripheral name */
#define BOARD_INITCS42448PINS_FC6_DATA_SIGNAL RXD_SDA_MOSI_DATA       /*!<@brief Signal name */
                                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCS42448Pins(void); /* Function assigned for the Cortex-M33 */

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name FC0_RXD_SDA_MOSI_DATA (coord H15), JP40[2]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITDEBUGCONSOLEPINS_DEBUG_UART_RXD_PERIPHERAL FLEXCOMM0
/*!
 * @brief Signal name */
#define BOARD_INITDEBUGCONSOLEPINS_DEBUG_UART_RXD_SIGNAL RXD_SDA_MOSI_DATA
/* @} */

/*! @name FC0_TXD_SCL_MISO_WS (coord H16), J16[1]/U27[3]/U9[12]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITDEBUGCONSOLEPINS_DEBUG_UART_TXD_PERIPHERAL FLEXCOMM0
/*!
 * @brief Signal name */
#define BOARD_INITDEBUGCONSOLEPINS_DEBUG_UART_TXD_SIGNAL TXD_SCL_MISO_WS
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDebugConsolePins(void); /* Function assigned for the Cortex-M33 */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
